images:
  brick:
    src: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/redbrick.svg
    alt: Redbrick logo
  emote:
    src: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/resign-emote.png
    alt: Discord emote
  logo:
    src: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/logo.png
    alt: Redbrick Logo
society:
  name: Redbrick
  tagline: DCU's Networking Society.
navigation:
  global:
    - text: Blog
      link: /blog/
    - text: Open Governance
      link: /open-governance/
    - text: Tech Docs
      link: https://docs.redbrick.dcu.ie
    - text: Wiki
      link: https://wiki.redbrick.dcu.ie
    - text: Links
      link: /links
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Signup
      link: https://join.redbrick.dcu.ie
    secondary:
      text: Discord
      link: https://discord.redbrick.dcu.ie
drawer: navigation
home:
  hero:
    title:
      secondary: DCU's Networking Society.
      primary: Become a Member.
    body: Redbrick was formed from a battered 386 PC (dubbed Nurse) and bits of borrowed memory - these days we spend our time running tech events for our members and deploying services. We’re open to everyone, regardless of computing level, who want to come and learn!
    buttons:
      primary:
        text: Signup
        link: https://join.redbrick.dcu.ie
      secondary:
        text: Discord
        link: https://discord.redbrick.dcu.ie
    graphic:
      image1:
        image: https://img.redbrick.dcu.ie/250x175/https://cdn.redbrick.dcu.ie/atlas/static/img/hackerdom.jpg
        alt: Wizzdom Hackerclub
      image2:
        image: https://media.discordapp.net/stickers/1170064614973788270.png
        alt: Distro Bopping
      image3:
        image: https://img.redbrick.dcu.ie/300x150/https://cdn.redbrick.dcu.ie/atlas/static/img/groupbanner.jpg
        alt: SIG Event
      image4:
        image: https://img.redbrick.dcu.ie/150x150/https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-mag1c.webp
        alt: SISTEM crew
      image5:
        image: https://img.redbrick.dcu.ie/150x200/https://cdn.redbrick.dcu.ie/atlas/static/img/hackergroup.jpg
        alt: Hackerclub crew
      image6:
        alt: Discord emote
      image7:
        alt: Redbrick logo
  cta:
    title: Don't Miss Out
    body: Redbrick hosts events for everything tech related - from computer programming tutorials to workshops with multinational tech companies.
    button:
      text: Signup
      link: https://join.redbrick.dcu.ie
    gallery:
      r1c1: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/hackersmovie.jpg
      r1c2: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/rbadmintalk.jpg
      r1c3: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/kamildeskrb.jpg
      r2c1: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/minecraft.jpg
      r2c2: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-mag1c.jpg
      r2c3: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/working.jpg
      r3c1: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/hecker.jpg
      r3c2: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/EGM2025.jpg
      r3c3: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/CSBall26.jpg
  committee:
    imageURL: https://img.redbrick.dcu.ie/150x275,fit/https://cdn.redbrick.dcu.ie/atlas/
    year: cmt25-26
    members:
     - name: Dominic Connor
       position: 🪑 Chair
       username: wizzdom
     - name: Shane Whelan
       position: 🪑 Vice-Chair
       username: pluto
     - name: Aoife Guanzon
       position: 💌 Secretary
       username: aoife
     - name: Jonathan Groult
       position: 💸 Treasurer
       username: nova
     - name: Harry Greenwood
       position: 📢 PRO
       username: mad
     - name: Kamil Kasza
       position: 🎨 GDO
       username: jstkamil
     - name: Ayden Jahola
       position: 🚀 SysAdmin
       username: ayden
     - name: Gavin Holahan
       position: 🚀 SysAdmin
       username: hypnoant
     - name: Conor Sludds
       position: 🚀 SysAdmin
       username: cj2364
     - name: Aris Sokianos
       position: 👾 Webmaster
       username: aris
     - name: Pavel Ivanov
       position: 🙌 Helpdesk
       username: regaus
     - name: Milan Tamang
       position: 🙌 Helpdesk
       username: milan
     - name: Edvard Tome
       position: 📅 Events Officer
       username: tome
     - name: Adam Wilkinson
       position: 📅 Events Officer
       username: wilko
     - name: Michal Wasiak
       position: 💎 Ordinary Member
       username: mehow
     - name: Eva Thunder
       position: 💎 Ordinary Member
       username: 3va
     - name: Pearse Cope
       position: 🥇 First Year Rep.
       username: pearse
