images:
  brick:
    src: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/redbrick.svg
    alt: Redbrick logo
  emote:
    src: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/resign-emote.png
    alt: Discord emote
  logo:
    src: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/logo.png
    alt: Redbrick Logo
society:
  name: Redbrick
  tagline: DCU's Networking Society.
navigation:
  global:
    - text: Blog
      link: /blog/
    - text: Open Governance
      link: /open-governance/
    - text: Tech Docs
      link: https://docs.redbrick.dcu.ie
    - text: Wiki
      link: https://wiki.redbrick.dcu.ie
    - text: Links
      link: /links
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Sign Up!
      link: https://join.redbrick.dcu.ie
    secondary:
      text: Discord
      link: https://discord.redbrick.dcu.ie
drawer: navigation

home:
  hero:
    title:
      secondary: DCU's Networking Society.
      primary: Become a Member.
    body: Redbrick was formed from a battered 386 PC (dubbed Nurse) and bits of borrowed memory - these days we spend our time running tech events for our members and deploying services. We’re open to everyone, regardless of computing level, who want to come and learn!
    buttons:
      primary:
        text: Sign Up!
        link: https://join.redbrick.dcu.ie
      secondary:
        text: Learn More!
        link: "#about"
    graphic:
      image1:
        image: https://img.redbrick.dcu.ie/230x170/https://cdn.redbrick.dcu.ie/atlas/static/img/hackerdom.jpg
        alt: Wizzdom Hackerclub
      image2:
        image: https://media.discordapp.net/stickers/1170064614973788270.png
        alt: Distro Bopping
      image3:
        image: https://img.redbrick.dcu.ie/250x140/https://cdn.redbrick.dcu.ie/atlas/static/img/groupbanner.jpg
        alt: Susquehanna Event
      image4:
        image: https://img.redbrick.dcu.ie/150x150/https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-mag1c.webp
        alt: SISTEM crew
      image5:
        image: https://img.redbrick.dcu.ie/220x160/https://cdn.redbrick.dcu.ie/atlas/static/img/hackergroup.jpg
        alt: Hackerclub crew
      image6:
        alt: Discord emote
      image7:
        alt: Redbrick logo

  cta:
    title: Don't Miss Out
    body: Redbrick hosts events for everything tech related - from computer programming tutorials to workshops with multinational tech companies.
    button:
      text: Signup
      link: https://join.redbrick.dcu.ie
    gallery:
      r1c1: https://img.redbrick.dcu.ie/500x250/https://cdn.redbrick.dcu.ie/atlas/static/img/hackersmovie.jpg
      r1c2: https://img.redbrick.dcu.ie/500x250/https://cdn.redbrick.dcu.ie/atlas/static/img/rbadmintalk.jpg
      r1c3: https://img.redbrick.dcu.ie/500x250/https://cdn.redbrick.dcu.ie/atlas/static/img/kamildeskrb.jpg
      r2c1: https://img.redbrick.dcu.ie/500x250/https://cdn.redbrick.dcu.ie/atlas/static/img/minecraft.jpg
      r2c2: https://img.redbrick.dcu.ie/500x250/https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-mag1c.jpg
      r2c3: https://img.redbrick.dcu.ie/500x250/https://cdn.redbrick.dcu.ie/atlas/static/img/jamestalk.jpg
      r3c1: https://img.redbrick.dcu.ie/500x250/https://cdn.redbrick.dcu.ie/atlas/static/img/hecker.jpg
      r3c2: https://img.redbrick.dcu.ie/500x250/https://cdn.redbrick.dcu.ie/atlas/static/img/EGM2025.jpg
      r3c3: https://img.redbrick.dcu.ie/500x250/https://cdn.redbrick.dcu.ie/atlas/static/img/CSBall26.jpg
  committee:
    imageURL: https://img.redbrick.dcu.ie/150x275/https://cdn.redbrick.dcu.ie/atlas/
    year: cmt26-27
    members:
     - name: Adam Wilkinson
       position: 🪑 Chair
       username: wilko
     - name: Gavin Holahan
       position: 🪑 Vice-Chair
       username: hypnoant
     - name: Joshua Farrell
       position: 💌 Secretary
       username: joshfarr
     - name: Jonathan Groult
       position: 💸 Treasurer
       username: nova
     - name: Edvard Tome
       position: 📢 PRO
       username: tome
     - name: Kamil Kasza
       position: 🎨 GDO
       username: jstkamil
     - name: Aris Sokianos
       position: 🚀 SysAdmin
       username: aris
     - name: Liam Kelly
       position: 🚀 SysAdmin
       username: graggle
     - name: Conor Sludds
       position: 🚀 SysAdmin
       username: cj2364
     - name: Chris Geng
       position: 👾 Webmaster
       username: cg_5228
     - name: Niall Carrick
       position: 🙌 Helpdesk
       username: nibbles
     - name: Eoghan Hughes
       position: 🙌 Helpdesk
       username: s_rogue
     - name: Milan Tamang
       position: 📅 Events Officer
       username: milan
     - name: Ben Adams
       position: 📅 Events Officer
       username: ben15
     - name: Aoife Guanzon
       position: 💎 Ordinary Member
       username: aoife
     - name: Pearse Cope
       position: 💎 Ordinary Member
       username: pearse
    #  - name: Pearse Cope
    #    position: 🥇 First Year Rep.
    #    username: pearse
  about:
    heading: About Us!
    graphic:
      image1:
        image: https://img.redbrick.dcu.ie/410x310/https://cdn.redbrick.dcu.ie/atlas/static/img/agm2026.jpg
        alt: AGM 2026
      image2:
        image: https://img.redbrick.dcu.ie/480x160/https://cdn.redbrick.dcu.ie/atlas/static/img/banner-medium.png
        alt: Rebrick Banner
      image3:
        image: https://img.redbrick.dcu.ie/400x200/https://cdn.redbrick.dcu.ie/atlas/static/img/handover-25.jpg
        alt: Committee handover 2025
      image4:
        image: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/logo.png
        alt: Redbrick Logo
      image5:
        image: https://img.redbrick.dcu.ie/150x190/https://cdn.redbrick.dcu.ie/atlas/static/img/open-day.jpg
        alt: Ayden and Hypnoant at DCU Open Day
  events:
    heading: Events
    graphic:
      image1:
        image: https://cdn.redbrick.dcu.ie/atlas/static/img/hackerclub-homelab.png
        alt: Homelab Hackerclub poster
      image2:
        image: https://img.redbrick.dcu.ie/400x200/https://cdn.redbrick.dcu.ie/atlas/static/img/valen-event-16-9.jpg
        alt: Talk with Valen
      image3:
        image: https://img.redbrick.dcu.ie/300x150/https://cdn.redbrick.dcu.ie/atlas/static/img/groupbanner.jpg
        alt: Susquehanna Event
      image4:
        image: https://img.redbrick.dcu.ie/150x150/https://cdn.redbrick.dcu.ie/atlas/static/img/susq-event.png
        alt: SISTEM crew
      image5:
        image: https://img.redbrick.dcu.ie/300x150/https://cdn.redbrick.dcu.ie/atlas/static/img/tarma-workshop.jpg
        alt: Susquehanna Workshop
