images:
  brick:
    src: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/redbrick.svg
    alt: Redbrick logo
  emote:
    src: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/resign-emote.png
    alt: Discord emote
  logo:
    src: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/logo.png
    alt: Redbrick Logo
society:
  name: Redbrick
  tagline: DCU's Networking Society.
navigation:
  global:
    - text: Blog
      link: /blog/
    - text: Open Governance
      link: /open-governance/
    - text: Tech Docs
      link: https://docs.redbrick.dcu.ie
    - text: Wiki
      link: https://wiki.redbrick.dcu.ie
    - text: Links
      link: /links
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Signup
      link: https://join.redbrick.dcu.ie
    secondary:
      text: Discord
      link: https://discord.redbrick.dcu.ie
drawer: navigation
home:
  hero:
    title:
      secondary: DCU's Networking Society.
      primary: Become a Member.
    body: Redbrick was formed from a battered 386 PC (dubbed Nurse) and bits of borrowed memory - these days we spend our time running tech events for our members and deploying services. We’re open to everyone, regardless of computing level, who want to come and learn!
    buttons:
      primary:
        text: Signup
        link: https://join.redbrick.dcu.ie
      secondary:
        text: Discord
        link: https://discord.redbrick.dcu.ie
    graphic:
      image1:
        image: https://img.redbrick.dcu.ie/150x150/https://cdn.redbrick.dcu.ie/atlas/static/img/newsletter-snap.webp
        alt: Baxter, Browner and Magma
      image2:
        image: https://media.discordapp.net/stickers/1170064614973788270.png
        alt: Distro Bopping
      image3:
        image: https://img.redbrick.dcu.ie/300x150/https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-banner.webp
        alt: SISTEM
      image4:
        image: https://img.redbrick.dcu.ie/150x150/https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-mag1c.webp
        alt: SISTEM crew
      image5:
        image: https://img.redbrick.dcu.ie/150x200/https://cdn.redbrick.dcu.ie/atlas/static/img/mail-broke.webp
        alt: Mail Broke
      image6:
        alt: Discord emote
      image7:
        alt: Redbrick logo
  cta:
    title: Don't Miss Out
    body: Redbrick hosts events for everything tech related - from computer programming tutorials to workshops with multinational tech companies.
    button:
      text: Signup
      link: https://join.redbrick.dcu.ie
    gallery:
      r1c1: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/tagging-24.jpg
      r1c2: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/newsletter-snap.webp
      r1c3: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/hacker.jpg
      r2c1: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/browner-explains.jpg
      r2c2: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-mag1c.jpg
      r2c3: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/working.jpg
      r3c1: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/hecker.jpg
      r3c2: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/cmt-24-25.jpg
      r3c3: https://img.redbrick.dcu.ie/1000x500/https://cdn.redbrick.dcu.ie/atlas/static/img/CSBallCmt24.jpg
  committee:
    - name: Jake Farrell
      position: 🪑 Chair
      username: cheese
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/cheese.png
    - name: Ishita Gupta
      position: 🪑 Vice-Chair
      username: ishitag
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/ishitag.jpg
    - name: Daniel Mc Entee
      position: 💌 Secretary
      username: kronos
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/kronos.png
    - name: Malavika Shanker
      position: 💸 Treasurer
      username: calcifer
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/calcifer.png
    - name: Philip Leonard
      position: 📢 PRO
      username: payne
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/payne.png
    - name: Georgijs Pitkevics
      position: 🎨 GDO
      username: zx
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/zx.jpg
    - name: Dominic Connor
      position: 🚀 SysAdmin
      username: wizzdom
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/wizzdom.png
    - name: Ayden Jahola
      position: 🚀 SysAdmin
      username: ayden
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/ayden.jpg
    - name: Gavin Holahan
      position: 🚀 SysAdmin
      username: hypnoant
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/hypnoant.png
    - name: Jonathan Groult
      position: 👾 Webmaster
      username: nova
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/nova.jpg
    - name: Pavel Ivanov
      position: 🙌 Helpdesk
      username: regaus
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/regaus.jpg
    - name: Konstantin O'Donnell
      position: 🙌 Helpdesk
      username: xoreax
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/xoreax.jpg
    - name: Shane Whelan
      position: 📅 Events Officer
      username: pluto
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/pluto.jpg
    - name: Edvard Tome
      position: 📅 Events Officer
      username: tome
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/tome.jpg
    - name: Claudia Gray
      position: 💎 Ordinary Member
      username: claudiaa
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/claudiaa.png
    - name: Henri Simmons-Hayden
      position: 💎 Ordinary Member
      username: henri117
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/henri117.jpg
    - name: Kamil
      position: 🥇 First Year Rep.
      username: jstkamil
      image: https://img.redbrick.dcu.ie/150x275,sc/https://cdn.redbrick.dcu.ie/atlas/cmt24-25/jstkamil.jpg
  events:
    api: https://clubsandsocs.jakefarrell.ie/dcuclubsandsocs.ie/society/redbrick
    graphic:
      image1:
        src: https://img.redbrick.dcu.ie/150x150/https://cdn.redbrick.dcu.ie/atlas/static/img/newsletter-snap.webp
        alt: Baxter, Browner and Magma
      image2:
        src: https://img.redbrick.dcu.ie/150x150/https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-mag1c.webp
        alt: SISTEM crew
      image3:
        src: https://img.redbrick.dcu.ie/300x150/https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-banner.webp
        alt: SISTEM
      image4:
        src: https://img.redbrick.dcu.ie/150x200/https://cdn.redbrick.dcu.ie/atlas/static/img/mail-broke.webp
        alt: Mail Broke
