images:
  roundel: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/cspp.svg
  embed: https://raw.githubusercontent.com/cs-soc-tudublin/IdentityFlip/master/assets/logos/roundel.png
society:
  name: CS++
  tagline: TU Dublin's Computer Science Society.
navigation:
  global:
    - text: Blog
      link: /blog/postmortems/downtime-postmortem-20-04.html
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Sign Up!
      link: https://join.cspp.ie
    secondary:
      text: Discord
      link: https://discord.cspp.ie
drawer: navigation
home:
  hero:
    title:
      secondary: TU Dublin's Computer Science Society.
      primary: Up for grabs!
    body: CS++ got its name in 2022, and traces its history back to 1998 with one goal; to aid its members - today, we help our members with their coursework, and give them access to invaluable experiences and skills!
    buttons:
      primary:
        text: Sign Up!
        link: https://join.cspp.ie
        aria: Link to the Clubs and Socs portal to join the society!
      secondary:
        link: https://instagram.com/tudublincsplusplus
        aria: Link to our Instagram page!
      tertiary:
        link: https://discord.cspp.ie
        aria: Link to our Discord server!
  cta:
    title: Don't Miss Out!
    body: CS++ runs events of all kinds, provides discounted tickets to conferences, and helps you academically.
    button:
      text: Sign Up Today!
      link: https://join.cspp.ie/
  committee:
    - name: Helena Garcia
      position: 🪑 Chair
      username: lehgarciafhs
      image: ./assets/img/committee/helena.webp
    - name: Anmool Shah
      position: 🪑 Vice-Chair
      username: anmool
      image: ./assets/img/committee/anmool.webp
    - name: Clara Rosell
      position: 💌 Secretary
      username: cr5706
      image: ./assets/img/committee/clara.webp
    - name: Arturo Lopez Lozada
      position: 💸 Treasurer
      username: iwatani
      image: ./assets/img/committee/arturo.webp
    - name: Lívia Guimarães
      position: 📢 PRO
      username: livguimaraes
      image: ./assets/img/committee/liv.webp
    - name: Georgin Jobin
      position: 👩‍⚕️ HSO
      username: gj07
      image: ./assets/img/committee/georgin.webp
    - name: Up for grabs!
      position: 💻 Tech Events Officer
      username: bitflip
      image: ./assets/img/committee/unknown.webp
    - name: Up for grabs!
      position: 🥳 Social Events Officer
      username: bitflip
      image: ./assets/img/committee/unknown.webp
    - name: Daniel Smyth
      position: 🚀 SysAdmin
      username: rockerkemm
      image: ./assets/img/committee/dan.webp
    - name: MJ
      position: 🚀 SysAdmin
      username: mjm
      image: ./assets/img/committee/mj.webp
    - name: Tyler Brady
      position: 🚀 SysAdmin
      username: relyT
      image: ./assets/img/committee/tyler.webp
    - name: Jack Burdis
      position: 🚀 SysAdmin
      username: burdisso
      image: ./assets/img/committee/jack.webp
    - name: Teodor Stoyanov
      position: 🚀 SysAdmin
      username: to60
      image: ./assets/img/committee/teodor.webp
    - name: Tan Winnie
      position: 🗓️ Events Rep
      username: ???
      image: ./assets/img/committee/unknown.webp
    - name: Up for grabs!
      position: 👼 First Year Rep
      username: bitflip
      image: ./assets/img/committee/unknown.webp
    - name: Up for grabs!
      position: 😅 Second Year Rep
      username: bitflip
      image: ./assets/img/committee/unknown.webp
  sponsorSection:
    enquiryStart: Want to be part of something great?
    enquiryEnd: Get in touch!
    enquiryLink: mailto:comp@societies.tudublin.ie?subject=Sponsorship Inquiry
  sponsors:
    - name: Rewriting the Code
      image: ./assets/img/sponsors/rtc.webp
      link: https://rewritingthecode.org/
      tier: General Sponsor
      weight: normal
      colour: normal
    - name: Accenture
      image: ./assets/img/sponsors/accenture.png
      link: https://www.accenture.com/ie-en
      tier: Main Sponsor
      weight: bold
      colour: primary

url: https://cspp.ie
footer:
  credit: Powered by Redbrick's Atlas System
